version: '3.0'

services:
  postgres:
    image: postgres:16.1
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipe-book
